version: '3.1'
networks:
  panel:
volumes:
  rogole-unison-sync:
    external: true
services:
  web:
    container_name: web
    image: rogolezhou/nginx1215
    ports:
      - "${app}:80"
      - "${php}:82"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - rogole-unison-sync:/mnt/app:nocopy
    networks:
      - panel
  php:
    container_name: php
    image: rogolezhou/php74-fpm:panel
    volumes:
      - rogole-unison-sync:/mnt/app:nocopy
      - /etc/localtime:/etc/localtime
    networks:
      - panel
    tty: true
  db:
    container_name: db
    image: mariadb:10.6
    secrets:
      - mysql_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_USER=panel
      - MYSQL_DATABASE=panel
    networks:
      - panel
    volumes:
      - ./services/sql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - panel
    secrets:
      - mysql_password
    environment:
      - PMA_HOST=db
      - PMA_USER=panel
      - PMA_PASSWORD_FILE=/run/secrets/mysql_password
secrets:
  mysql_password:
    file: .DBsecrets