version: '3'
networks:
  panel:
services:
  web:
    container_name: web
    image: nginx
    ports:
      - "${app}:80"
      - "${php}:81"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ./app:/mnt/app
    networks:
      - panel
  php:
    container_name: php
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
      - /etc/localtime:/etc/localtime
    networks:
      - panel
    tty: true
  db:
    container_name: db
    image: mariadb:10.6
    secrets:
      - mysql_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_USER=panel
      - MYSQL_DATABASE=panel
    networks:
      - panel
    volumes:
      - ./services/sql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
secrets:
  mysql_password:
    file: .DBsecrets